language: objective-c
osx_image: xcode9

before_install:
  - gem install xcpretty

script:
    - xcodebuild clean build -sdk iphonesimulator -workspace NeuralSwift.xcworkspace -scheme NeuralSwift CODE_SIGNING_REQUIRED=NO | xcpretty